### ISSUE TITLE
Error loading .sat file

### ISSUE THREAD

**Issue by eldir** [jmplonka/InventorLoader#60]
I'm getting an error trying to load a .sat file. Let me know if you need more information! It's a fresh installation of FreeCAD.

### FreeCAD About
```
OS: Windows 10 Version 2009
Word size of FreeCAD: 64-bit
Version: 0.20.29177 (Git)
Build type: Release
Branch: releases/FreeCAD-0-20
Hash: 68e337670e227889217652ddac593c93b5e8dc94
Python 3.8.10, Qt 5.15.2, Coin 4.0.1, Vtk 8.2.0, OCC 7.6.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * InventorLoader 1.3.0
```

### Error Message
```
10:13:19  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\eldir\AppData\Roaming\FreeCAD\Mod\InventorLoader\.\importerIL.py", line 147, in open
    _open(filename, skip, only, root)
  File "C:\Users\eldir\AppData\Roaming\FreeCAD\Mod\InventorLoader\.\importerIL.py", line 127, in _open
    reader = read(filename)
  File "C:\Users\eldir\AppData\Roaming\FreeCAD\Mod\InventorLoader\.\importerIL.py", line 46, in read
    if (importerSAT.readText(filename)):
  File "C:\Users\eldir\AppData\Roaming\FreeCAD\Mod\InventorLoader\.\importerSAT.py", line 163, in readText
    result = reader.readText()
  File "C:\Users\eldir\AppData\Roaming\FreeCAD\Mod\InventorLoader\.\Acis.py", line 4952, in readText
    self._readHeaderText()
  File "C:\Users\eldir\AppData\Roaming\FreeCAD\Mod\InventorLoader\.\Acis.py", line 4851, in _readHeaderText
    self.date,    data = getNextText(data)
  File "C:\Users\eldir\AppData\Roaming\FreeCAD\Mod\InventorLoader\.\Acis.py", line 4705, in getNextText
    count = int(m.group(1))
<class 'AttributeError'>: 'NoneType' object has no attribute 'group'
```

**Comment by luzpaz** [comment]
Can you include the file?

**Comment by eldir** [comment]
I'm afraid I cannot share the entire file, but I can share the header and the tail if that helps

```
500 0 2 0 
58 PRO/ENGINEER BY PARAMETRIC TECHNOLOGY CORPORATION, 2015480 8 ACIS 7.0 24
Tue Mar 13 09:58:36 2018 
1 0.030172922507418501 1e-10 
-0 body $-1 $-1 $-1 $2 #
```

```
0.99999999999999967 0 0 0 0 -0.15240000000000009 1 F 0 F 3.1415926535897931 #
End-of-ACIS-data

```

**Comment by drTusse** [comment]
I have the exakt same issue with a .sat file, I receive the very same error message. Any chance there's a fix? Same for me, I cannot share the file unfortunately

**Comment by HolographicPrince** [comment]
If you don't include the file how do you think this error cna be fixed? It's a trivial parsing error and ACIS has so many dialects.

**Comment by jmplonka** [comment]
@drTusse : Coult you please send me a test file?
