### ISSUE TITLE
Access violation when importing ipt as step file.

### ISSUE THREAD

**Issue by Herrcookiekiller** [jmplonka/InventorLoader#80]
When i try to import an .ipt file and choose "convert to step" i get this error thrown at me.
```
13:15:56  Importing: C:/Users/-/Downloads/lampenblech_aussen.ipt
13:15:58  Failed to create shell -9 shell $-1 -1 $-1 $-1 $-1 $-1 $15 $5 #
13:15:58  Failed to create shell -14 shell $-1 -1 $-1 $-1 $-1 $-1 $25 $8 #
13:15:58  Failed to create shell -24 shell $-1 -1 $-1 $-1 $-1 $-1 $39 $13 #
13:15:58  Failed to create shell -38 shell $-1 -1 $-1 $-1 $-1 $-1 $58 $23 #
13:15:58  Failed to create shell -57 shell $-1 -1 $-1 $-1 $-1 $-1 $92 $37 #
13:15:58  Failed to create shell -91 shell $-1 -1 $-1 $-1 $-1 $-1 $151 $56 #
13:15:58  Failed to create shell -150 shell $-1 -1 $-1 $-1 $-1 $-1 $229 $90 #
13:15:58  Failed to create shell -228 shell $-1 -1 $-1 $-1 $-1 $-1 $319 $149 #
13:15:58  Failed to create shell -11 shell $-1 -1 $-1 $-1 $-1 $-1 $18 $6 #
13:15:58  Failed to create shell -17 shell $-1 -1 $-1 $-1 $-1 $-1 $29 $10 #
13:15:58  Failed to create shell -28 shell $-1 -1 $-1 $-1 $-1 $-1 $44 $16 #
13:15:58  Failed to create shell -43 shell $-1 -1 $-1 $-1 $-1 $-1 $67 $27 #
13:15:58  Failed to create shell -66 shell $-1 -1 $-1 $-1 $-1 $-1 $106 $42 #
13:15:58  Failed to create shell -105 shell $-1 -1 $-1 $-1 $-1 $-1 $166 $65 #
13:15:58  Failed to create shell -165 shell $-1 -1 $-1 $-1 $-1 $-1 $244 $104 #
13:15:58  Failed to create shell -243 shell $-1 -1 $-1 $-1 $-1 $-1 $334 $164 #
13:15:58  Failed to create shell -333 shell $-1 -1 $-1 $-1 $-1 $-1 $435 $242 #
13:15:58  Failed to create shell -434 shell $-1 -1 $-1 $-1 $-1 $-1 $546 $332 #
13:15:58  Failed to create shell -545 shell $-1 -1 $-1 $-1 $-1 $-1 $652 $433 #
13:15:58  Failed to create shell -651 shell $-1 -1 $-1 $-1 $-1 $-1 $755 $544 #
13:15:58  Failed to create shell -754 shell $-1 -1 $-1 $-1 $-1 $-1 $856 $650 #
13:15:58  Failed to create shell -855 shell $-1 -1 $-1 $-1 $-1 $-1 $945 $753 #
13:15:58  Failed to create shell -944 shell $-1 -1 $-1 $-1 $-1 $-1 $1022 $854 #
13:15:58  Failed to create shell -1021 shell $-1 -1 $-1 $-1 $-1 $-1 $1075 $943 #
13:15:58  Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\-\AppData\Roaming\FreeCAD\Mod\InventorLoader\.\importerIL.py", line 118, in insert
    reader.create3dModel(group, doc)
  File "C:\Users\-\AppData\Roaming\FreeCAD\Mod\InventorLoader\.\Import_IPT.py", line 279, in create3dModel
    convertModel(root, doc.Name)
  File "C:\Users\-\AppData\Roaming\FreeCAD\Mod\InventorLoader\.\importerSAT.py", line 151, in convertModel
    ImportGui.insert(stepfile, docName)
<class 'OSError'>: Access violation
```

However, when i import another ipt file from the same Inventor Project, it works, i get my step file and everything works, but its still throwing an error at me. Even though 

```
13:19:48  Importing: C:/Users/-/Downloads/Zylinder - Frästeil lang3.ipt
13:19:49  ERROR> importerDC.py missing 'def Read_2D7FC491(self, node)'!
```
Could the first error and the resulting failed import + conversion process be caused by a too complex ipt part?

Also, the first part is a sheet metal part in Inventor, this might be causing problems.
I have the sheet metal workbench installed, as it is a dependancy for InventorLoader.

Maybe unrelated, but this is the second part that correctly imported. The folder structure in the treeview is a bit weird.
Could this be caused by the seemingly unrelated error?

![grafik](https://github.com/jmplonka/InventorLoader/assets/40491077/13e03cf1-7438-4cce-8ce3-5be61882eab6)

**Comment by luzpaz** [comment]
bump

**Comment by marcocecchiscmgroup** [comment]
Providing lampenblech_aussen.ipt could be a good starting point...
